---
- hosts: webservers
  become: yes
  tasks:
    - name: Install Apache2
      yum:
        name: apache2
        update_cache: yes
        state: present
    - name: Ensure apache is running
    service:
        name: apache2
        state: started
        enabled: yes
